basket/urls.py
from django.urls import path
import basket.views

app_name = 'basket'

urlpatterns = [
    path('', basket.views.basket_detail, name='basket_detail'),
    path('add/<int:product_id>/', basket.views.basket_add, name='basket_add'),
    path('remove/<int:product_id>/', basket.views.basket_remove, name='basket_delete'),
    path('plus_item/<int:product_id>/', basket.views.plus_item, name='plus_item'),
    path('minus_item/<int:product_id>/', basket.views.minus_item, name='minus_item'),
    path('create/', basket.views.order_create, name='order_create'),
    path('complete/', basket.views.order_complete, name='order_complete'),
]

core/urls.py
from django.urls import path
import core.views

app_name = 'core'

urlpatterns = [
    path('', core.views.IndexView.as_view(), name='home'),
    path('catalog/', core.views.ProductList.as_view(), name='catalog'),
    path('catalog/category/<int:category_id>/', core.views.ProductList.as_view(), name='category'),
    path('catalog/create', core.views.ProductCreate.as_view(), name='product_create'),
    path('catalog/product/<int:pk>/delete/', core.views.ProductDelete.as_view(), name='product_delete'),
    path('catalog/product/<int:pk>/update/', core.views.ProductUpdate.as_view(), name='product_update'),
    path('catalog/product/<int:pk>/', core.views.ProductDetail.as_view(), name='products'),
    path('catalog/product/add_review/<int:pk>/', core.views.Review.as_view(), name='review'),
    path('pharmacy/', core.views.PharmacyList.as_view(), name='pharmacy'),
    path('pharmacy/<int:pharmacy_id>/', core.views.ProductInPharmacy.as_view(), name='product_in_pharmacy'),
]

project/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('users/', include('users.urls', namespace='users')),
    path('basket/', include('basket.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static('node_modules', document_root=os.path.join(settings.BASE_DIR, 'node_modules'))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket/models.py
from django.db import models
from core.models import Product
from django.contrib.auth.models import User


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def get_cost(self):
        return self.price * self.quantity

basket/forms.py
from django import forms
from basket.models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

basket/views.py
from django.shortcuts import render, redirect, get_object_or_404
from core.models import Product
from .basket import Basket
from basket.forms import OrderCreateForm
from basket.models import OrderItem, Order


def basket_detail(request):
    basket = Basket(request)
    return render(request, 'basket/basket_detail.html', {'basket': basket})


def basket_add(request, product_id):
    basket = Basket(request)
    product = get_object_or_404(Product, id=product_id)
    basket.add(product=product)
    return redirect('basket:basket_detail')


def basket_remove(request, product_id):
    basket = Basket(request)
    product = get_object_or_404(Product, id=product_id)
    basket.remove(product)
    return redirect('basket:basket_detail')


def plus_item(request, product_id):
    basket = Basket(request)
    product = get_object_or_404(Product, id=product_id)
    basket.plus(product=product)
    return redirect('basket:basket_detail')


def minus_item(request, product_id):
    basket = Basket(request)
    product = get_object_or_404(Product, id=product_id)
    basket.minus(product=product)
    return redirect('basket:basket_detail')


def order_create(request):
    basket = Basket(request)
    order = Order.objects.create(user=request.user)
    for item in basket:
        OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])
    basket.clear()
    return render(request, 'basket/create.html', {'basket': basket, 'order': order})


def order_complete(request):
    return render(request, 'basket/created.html')

basket/templates/basket/basket_detail.html
{% extends "core/base.html" %}
{% block content %}
<button type="button" class="btn btn-light"><a href="{% url 'core:catalog' %}">Назад</a></button>
<h1> Корзина </h1>
<table class="table">
    <thead>
    <tr>
        <th>Товар</th>
        <th>Количество</th>
        <th>Цена за штуку</th>
        <th>Стоимость</th>
        <th><i class="fa-solid fa-plus"></i></th>
        <th><i class="fa-solid fa-minus"></i></th>
        <th>Удалить</th>
    </tr>
    </thead>
    <tbody>
    {% for item in basket %}
    {% with product=item.product %}
    <tr>
        <td>{{ product.name }}</td>
        <td>{{ item.quantity }}</td>
        <td class="num">₽{{ item.price }}</td>
        <td class="num">₽{{ item.total_price }}</td>
        <td>
            <form method="post" action="{% url 'basket:plus_item' product.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary"><i class="fa-solid fa-plus"></i></button>
            </form>
        </td>
        <td>
            <form method="post" action="{% url 'basket:minus_item' product.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary"><i class="fa-solid fa-minus"></i></button>
            </form>
        </td>
        <td>
            <form method="post" action="{% url 'basket:basket_delete' product.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary"><i class="fa-solid fa-trash"></i></button>
            </form>
        </td>
    </tr>
    {% endwith %}
    {% endfor %}
    </tbody>
</table>
<h2> Итого: ₽{{ basket.get_total_price }}</h2>
<form method="post" action="{% url 'basket:order_create' %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-success">Оформить заказ</button>
</form>
{% endblock %}

basket/templates/basket/create.html
{% extends "core/base.html" %}
{% block content %}
<h1>Заказ</h1>
<h4> Покупатель: {{user}} </h4>
<h4> Детали заказа: </h4>
<ol class="list-group list-group-flush">
    {% for item in basket %}
    <li class="list-group-item">{{ item.quantity }}X {{ item.product.name }} ₽{{ item.total_price }}
    </li>
    {% endfor %}
    <h4>Итого: ₽{{ basket.get_total_price }}</h4>
</ol>
<form method="post" action="{% url 'basket:order_complete'%}">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Заказать</button>
</form>
{% endblock %}

basket/templates/basket/created.html
{% extends "core/base.html" %}
{% block content %}
<button type="button" class="btn btn-light"><a href="{% url 'core:catalog' %}">Назад</a></button>
    <h1>Спасибо!</h1>
    <p>Ваш заказ успешно выполнен!
{% endblock %}