basket/urls.py
from django.urls import path
import basket.views

app_name = 'basket'

urlpatterns = [
    path('', basket.views.basket_detail, name='basket_detail'),
    path('add/<int:product_id>/', basket.views.basket_add, name='basket_add'),
    path('remove/<int:product_id>/', basket.views.basket_remove, name='basket_delete'),
    path('plus_item/<int:product_id>/', basket.views.plus_item, name='plus_item'),
    path('minus_item/<int:product_id>/', basket.views.minus_item, name='minus_item'),
    path('create/', basket.views.order_create, name='order_create'),
    path('complete/', basket.views.order_complete, name='order_complete'),
]

core/urls.py
from django.urls import path
import core.views

app_name = 'core'

urlpatterns = [
    path('', core.views.IndexView.as_view(), name='home'),
    path('catalog/', core.views.ProductList.as_view(), name='catalog'),
    path('catalog/category/<int:category_id>/', core.views.ProductList.as_view(), name='category'),
    path('catalog/create', core.views.ProductCreate.as_view(), name='product_create'),
    path('catalog/product/<int:pk>/delete/', core.views.ProductDelete.as_view(), name='product_delete'),
    path('catalog/product/<int:pk>/update/', core.views.ProductUpdate.as_view(), name='product_update'),
    path('catalog/product/<int:pk>/', core.views.ProductDetail.as_view(), name='products'),
    path('catalog/product/add_review/<int:pk>/', core.views.Review.as_view(), name='review'),
    path('pharmacy/', core.views.PharmacyList.as_view(), name='pharmacy'),
    path('pharmacy/<int:pharmacy_id>/', core.views.ProductInPharmacy.as_view(), name='product_in_pharmacy'),
]

project/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('users/', include('users.urls', namespace='users')),
    path('basket/', include('basket.urls', namespace='basket')),
]

if settings.DEBUG:
    urlpatterns += static('node_modules', document_root=os.path.join(settings.BASE_DIR, 'node_modules'))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
import users.views

app_name = 'users'

urlpatterns = [
    path('login/', users.views.UserLoginView.as_view(), name='login'),
    path('logout/', users.views.UserLogoutView.as_view(), name='logout'),
    path('register/', users.views.UserRegisterView.as_view(), name='register'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField('Название категории', max_length=50, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField('Название товара', max_length=50, unique=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    type = models.CharField('Форма выпуска', max_length=50, blank=True)
    manufacturer = models.CharField('Производитель', max_length=20, blank=True, null=True)
    country = models.CharField('Страна производителя', max_length=15, blank=True, null=True)
    price = models.IntegerField('Цена товара')
    photo = models.ImageField('Изображение товара', upload_to='products/', blank=True)
    indications_for_use = models.TextField('Показания к применению', blank=True)
    mode_of_application = models.TextField('Способ применения', blank=True)
    composition = models.TextField('Состав', blank=True)
    contraindications = models.TextField('Противопоказания', blank=True)

    def __str__(self):
        return self.name


class Pharmacy(models.Model):
    name = models.CharField('Название аптеки', max_length=25)
    street = models.CharField("Улица", max_length=50, blank=True, null=True)
    house = models.IntegerField("Номер дома", blank=True, null=True)
    phone = models.IntegerField("Номер телефона", blank=True, null=True)
    photo = models.ImageField('Изображение аптеки', upload_to='pharmacies/', blank=True)
    opening_time = models.TimeField('Время открытия', default='9:00', blank=True)
    closing_time = models.TimeField('Время закрытия', default='21:00', blank=True)

    def __str__(self):
        return self.name


class Available(models.Model):
    pharmacy = models.ForeignKey('Pharmacy', on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField('Количество')

    def __str__(self):
        return f'{self.pharmacy} {self.product} {self.quantity}'


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    review = models.TextField('Отзыв')
    date = models.DateTimeField('Дата добавления', auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return self.review

core/forms.py
from django import forms
import core.models


class ProductEdit(forms.ModelForm):
    class Meta:
        model = core.models.Product
        fields = '__all__'

core/views.py
from django.db.models import Sum
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
import core.models
import core.filters
from django.urls import reverse
import core.forms


class TitleMixin:
    title = None

    def get_title(self):
        return self.title

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['title'] = self.get_title()
        return context


class IndexView(TitleMixin, TemplateView):
    template_name = 'core/index.html'
    title = 'Главная страница'


class ProductList(TitleMixin, ListView):
    title = 'Товары'
    context_object_name = 'products'

    def get_filters(self):
        return core.filters.ProductFilter(self.request.GET)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['category'] = core.models.Category.objects.all()
        context['review'] = core.models.Review.objects.all()
        context['filters'] = self.get_filters()
        return context

    def get_queryset(self):
        if not self.kwargs:
            qs = self.get_filters().qs
        else:
            qs = self.get_filters().qs.filter(category_id=self.kwargs['category_id'])
        return qs


class ProductDetail(TitleMixin, DetailView):
    model = core.models.Product
    title = 'Товар'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['review'] = core.models.Review.objects.all()
        return context


class Review(TitleMixin, CreateView):
    model = core.models.Review
    title = 'Добавление отзыва'
    template_name = 'core/review.html'
    fields = ['review']
    product = None

    def form_valid(self, form):
        form.instance.user = self.request.user
        self.product = form.instance.product = core.models.Product.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('core:products', kwargs={'pk': self.kwargs['pk']})


class PharmacyList(TitleMixin, ListView):
    title = 'Аптеки'

    def get_filters(self):
        return core.filters.PharmacyFilter(self.request.GET)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['filters'] = self.get_filters()
        return context

    def get_queryset(self):
        return self.get_filters().qs


class ProductInPharmacy(TitleMixin, ListView):
    title = 'Товары в наличии'
    model = core.models.Available

    def get_queryset(self):
        return core.models.Available.objects.filter(pharmacy_id=self.kwargs['pharmacy_id'])


class ProductUpdate(TitleMixin, UpdateView):
    model = core.models.Product
    form_class = core.forms.ProductEdit

    def get_title(self):
        return f'Изменение данных товара "{str(self.get_object())}"'

    def get_success_url(self):
        return reverse('core:catalog')


class ProductCreate(TitleMixin, CreateView):
    model = core.models.Product
    form_class = core.forms.ProductEdit
    title = 'Добавление товара'

    def get_success_url(self):
        return reverse('core:catalog')


class ProductDelete(TitleMixin, DeleteView):
    model = core.models.Product

    def get_title(self):
        return f'Удаление товара {str(self.get_object())}'

    def get_success_url(self):
        return reverse('core:catalog')

core/templates/core/available_list.html
{% extends 'core/base.html'  %}
{% block content %}

<table class="table">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Товар</th>
        <th scope="col">Количество</th>
    </tr>
    </thead>
    <tbody>
    {% for product in object_list %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{product.product}}</td>
        <td>{{product.quantity}}</td>
    </tr>
    {% empty %}
    <h2>Нет товаров</h2>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

core/templates/core/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/8878a43cf5.js" crossorigin="anonymous"></script>
    <title>{{ title }}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"><i class="fa-solid fa-briefcase-medical"></i> Сайт аптеки</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:catalog'%}">Каталог товаров</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:pharmacy'%}">Аптеки</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/admin/">Admin</a>
                </li>
                </li>
            </ul>
        </div>
        {% if user.is_authenticated%}
         <a class="nav-link" href="{% url 'basket:basket_detail' %}">Корзина <i class="fa-solid fa-basket-shopping"></i></a>
        <span class="navbar-text">{{ user.username }}</span>
        <a class="nav-link" href="{% url 'users:logout'%}">Выход</a>
        {% else %}
        <a class="nav-link" href="{% url 'users:login'%}">Войти</a> |
        <a class="nav-link" href="{% url 'users:register'%}">Регистрация</a>
        {% endif %}
    </div>
</nav>
{% block content%}
{% endblock %}
<script src="/node_modules/bootstrap/dist/js/bootstrap.bundle.js"></script>
</body>
</html>

core/templates/core/index.html
{% extends 'core/base.html'  %}
{% block content %}
<h1>Главная страница</h1>
{% endblock %}

core/templates/core/pharmacy_list.html
{% extends 'core/base.html'  %}
{% block content %}
{% include 'core/search_form_include.html' %}
<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for pharmacy in object_list %}
        <div class="col">
            <div class="card" style="width: 25rem; height: 25rem">
                {% if pharmacy.photo %}
                <img class="card-img-top" src="{{ pharmacy.photo.url }}"
                     style="width: 21rem; height: 15rem; object-fit: flex;">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'core:product_in_pharmacy' pharmacy.pk %}">{{ pharmacy.name }}</a></h5>
                    <p class="card-text">Адрес: ул. {{ pharmacy.street}}, дом {{ pharmacy.house}}</p>
                    <p class="card-text">Телефон: {{ pharmacy.phone}}</p>
                    <p class="card-text">Часы работы: {{ pharmacy.opening_time}} - {{ pharmacy.closing_time}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

core/templates/core/product_confirm_delete.html
{% extends 'core/base.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="alert alert-danger">
    Вы действительно хотите удалить "{{ object }}"?
</div>

<form method="post">{% csrf_token %}
    <button class="btn btn-danger" type="submit">
        Да
    </button>
    <button class="btn btn-success" onclick="location.href='{% url 'core:catalog' %}'" type="button">
        нет
    </button>
</form>

{% endblock %}

core/templates/core/product_detail.html
{% extends 'core/base.html'  %}
{% block content %}
    <button type="button" class="btn btn-light"><a href="{% url 'core:catalog' %}">Назад</a></button>
<div class="container-lg mt-5">
    {% if user.is_stuff or user.is_superuser%}
    <button class="btn btn-outline-danger" onclick="location.href='{% url 'core:product_delete' product.pk%}'"
            type="button" style="float: right;"> Удалить
    </button>
    <button class="btn btn-outline-success" onclick="location.href='{% url 'core:product_update' product.pk %}'"
            type="button" style="float: right;"> Изменить
    </button>
    {% endif %}
    {% if product.photo %}
    <img src="{{product.photo.url}}" class="rounded float-start" style="width: 28rem; height: 18rem; object-fit: flex;">
    {% endif %}
    <ul class="list-group list-group-flush mt-5">
        <li class="list-group-item"><h1> {{ product.name }} </h1></li>
        <li class="list-group-item"><h3> Цена: {{ product.price }} рублей </h3></li>
        <li class="list-group-item">Категория: {{ product.category }}</li>
        <li class="list-group-item">Форма выпуска: {{ product.type }}</li>
        <li class="list-group-item">Производитель: {{ product.manufacturer }}</li>
        <li class="list-group-item">Страна производитель: {{ product.country }}</li>
    </ul>
    <h3> Информация </h3>
    <div class="accordion accordion-flush" id="accordionFlushExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingOne">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                    Показания к применению
                </button>
            </h2>
            <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne"
                 data-bs-parent="#accordionFlushExample">
                <div class="accordion-body"> {{ product.indications_for_use }}</div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                    Способ применения
                </button>
            </h2>
            <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo"
                 data-bs-parent="#accordionFlushExample">
                <div class="accordion-body"> {{ product.mode_of_application }}</div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                    Состав
                </button>
            </h2>
            <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree"
                 data-bs-parent="#accordionFlushExample">
                <div class="accordion-body"> {{ product.composition }}</div>
            </div>
        </div>
        <div class="accordion-item">
            <h2 class="accordion-header" id="flush-headingFour">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#flush-collapseFour" aria-expanded="false" aria-controls="flush-collapseFour">
                    Противопоказания
                </button>
            </h2>
            <div id="flush-collapseFour" class="accordion-collapse collapse" aria-labelledby="flush-headingFour"
                 data-bs-parent="#accordionFlushExample">
                <div class="accordion-body"> {{ product.contraindications }}</div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <h3>Отзывы</h3>
            {% for rev in review %}
            <div class="card">
                <div class="card-body">
                    <h4>{{ rev.user }}</h4>
                    <p>{{ rev.review }}</p>
                    <p>{{ rev.date }}</p>
                </div>
            </div>
            {% endfor %}
            <button class="btn btn-outline-primary" onclick="location.href='{% url 'core:review' product.pk %}'"
                    type="button"> Добавить отзыв
            </button>
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/product_form.html
{% extends 'core/base.html' %}
{% load bootstrap5 %}
{% block content %}
<div style="width: 50%; margin: 1rem">
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="сохранить">
</form>
</div>
{% endblock %}

core/templates/core/product_list.html
{% extends 'core/base.html'  %}
{% block content %}
{% include 'core/search_form_include.html' %}
<div class="list-group list-group-horizontal">
    {% for cat in category %}
    <li class="list-group-item"><a href="{% url 'core:category' cat.pk %}"> {{ cat.name }}</a></li>
    {% endfor %}
</div>
<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for product in products %}
        <div class="col">
            <div class="card" style="width: 20rem; height: 25rem">
                {% if product.photo %}
                <img class="card-img-top" src="{{ product.photo.url }}"
                     style="width: 20rem; height: 15rem; object-fit: flex;">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'core:products' product.pk %}">{{ product.name }}</a></h5>
                    <p class="card-text">Цена: ₽{{ product.price}}</p>
                    {% if user.is_authenticated%}
                    <form method="post" action="{% url 'basket:basket_add' product.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success"> Добавить в корзину</button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
        {% if user.is_stuff or user.is_superuser%}
        <div class="col">
            <a href="{% url 'core:product_create' %}" style="text-decoration: none">
                <div class="card">
                    <div align="center" class="card-body">
                        <h1 class="card-title">+</h1>
                    </div>
                </div>
            </a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

core/templates/core/review.html
{% extends 'core/base.html' %}
{% block content %}
{% load bootstrap5 %}
<div style="width: 50%; margin: 1rem">
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button type="submit" class="btn btn-primary">готово</button>
        {% endbuttons %}
    </form>
</div>
{% endblock %}

core/templates/core/search_form_include.html
{% load bootstrap5 %}

<form class="row g-3" style="margin-top:1%">
    <div class="col-auto">
        {% bootstrap_form filters.form layout='horizontal' %}
    </div>
    <div class="col-auto">
        {% bootstrap_button "Поиск" button_type="submit" button_class="btn-primary"%}
    </div>
</form>